### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './models/dump/IMG_1.jpg.png'

### ISSUE THREAD

**Issue by SherlockHua1995** [val-iisc/lsc-cnn#13]
Hello, THANKS for your opensource.
I'd like to train the model by 
"python3 main.py --dataset="parta" --gpu=0 --start-epoch=0 --epochs=13 --threshold=0.21
"
but got "FileNotFoundError: [Errno 2] No such file or directory: './models/dump/IMG_1.jpg.png'"
I will check the source code to find out and any instruction would be appreciated.

**Comment by pvskand** [comment]
Just creating `models/dump` and `models/dump_test` folders should fix the error.

**Comment by SherlockHua1995** [comment]
Hello,here I come again~
Traceback (most recent call last):
  File "main.py", line 1108, in <module>
    train()
  File "main.py", line 1049, in train
    log_path=model_save_path)
  File "main.py", line 926, in train_networks
    epoch_test_losses, txt = test_lsccnn(test_funcs, dataset, 'test', network, True)
  File "main.py", line 653, in test_lsccnn
    for e_idx, e_iter in enumerate(e):
  File "/home/scu508/workspace/lsc-cnn/data_reader.py", line 281, in iterate_over_test_data
    pred_maps_full_size = self._test_one_image(crops, test_function)
  File "/home/scu508/workspace/lsc-cnn/data_reader.py", line 719, in _test_one_image
    results = test_function(img_batch, gt_batch, roi_batch)
  File "main.py", line 639, in test_function
    loss, pred_batch, gt_batch = test_funcs(img_batch, gt_batch, loss_weights, network)
  File "main.py", line 401, in test_function
    Yss_out = self.get_box_gt(Yss)
  File "main.py", line 166, in get_box_gt
    assert(check_sum == torch.sum(Yss[0][b]).item() == len(y_idx))
AssertionError
I HAVE read the code and didn't find the cause.
Thank you~
