### ISSUE TITLE
Datasetpatherror for UCF-QNRF

### ISSUE THREAD

**Issue by hendl** [val-iisc/lsc-cnn#15]
I tried to run the framework with the UCF Dataset but everytime I start the Test or Training process I get the following eror:

```
root@bf38862e4add:/lsc# python3 main.py --dataset="ucfqnrf" --gpu=1 --start-epoch=46 --epochs=46 --threshold=0.20

In data_reader.__init__: Can't read meta data in ../dataset/qnrf_dotmaps_predictionScale_2; call create_dataset_files.
{'test': ['../dataset/UCF-QNRF_ECCV18/Test/', '../dataset/UCF-QNRF_ECCV18/Test/'], 'train': ['../dataset/UCF-QNRF_ECCV18/Train/', '../dataset/UCF-QNRF_ECCV18/Train/']} <data_reader.DataReader object at 0x7fccccc43ef0>
CREATING DATASET...
In data_reader.create_dataset_files: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2/test.
In data_reader.create_dataset_files: ../dataset/qnrf_dotmaps_predictionScale_2/test created.
In data_reader.create_dataset_files: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2/train.
In data_reader.create_dataset_files: ../dataset/qnrf_dotmaps_predictionScale_2/train created.
In data_reader.create_dataset_files: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2/test_valid.
In data_reader.create_dataset_files: ../dataset/qnrf_dotmaps_predictionScale_2/test_valid created.
Processing img_0001.jpg ...
Traceback (most recent call last):
  File "main.py", line 1108, in <module>
    train()
  File "main.py", line 1029, in train
    test_batch_size=4)
  File "/lsc/data_reader.py", line 200, in create_dataset_files
    self._dump_all_test_images(set_name)
  File "/lsc/data_reader.py", line 826, in _dump_all_test_images
    data = self._read_image_and_gt_prediction(paths, file_name, kernel)
  File "/lsc/data_reader.py", line 789, in _read_image_and_gt_prediction
    'GT_' + tmp + '.mat'))
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable
```

My setup looks like this:
```
/lsc-cnn
   -- network.py
   -- main.py
   -- ....
/dataset
|-- UCF-QNRF_ECCV18
|   |-- Test
|   `-- Train
`-- qnrf_dotmaps_predictionScale_2
    |-- test
    |   |-- 0
    |   `-- 1
    |-- test_valid
    `-- train
```

I already tried to separate the images and mat files but I still get the same eror.
```
dataset_paths = {'test': ['../dataset/UCF-QNRF_ECCV18/Test/images',
                              '../dataset/UCF-QNRF_ECCV18/Test/ground-truth'],
                         'train': ['../dataset/UCF-QNRF_ECCV18/Train/images',
                               '../dataset/UCF-QNRF_ECCV18/Train/ground-truth']}
```

Can you please help me to specify the correct settings and paths?

**Comment by pvskand** [comment]
Hello,
I think the problem is in the dictionary keys (I'll update it later in the code). This should resolve the issue:
`data_mat = scipy.io.loadmat(os.path.join(paths[1], tmp + '_ann.mat'))`
`gt_annotation_points = data_mat['annPoints']`

Also for QNRF make sure you include the `--patches=30` argument while training. If you use the default configuration it would take a long time to train since the dataset is huge. (I'll add this in the README)

**Comment by hendl** [comment]
Thanks it's working now 😄

**Comment by ohlr** [comment]
@pvskand is  `gt_annotation_points -= 1`  still required after `gt_annotation_points = data_mat['annPoints']`?
