### ISSUE TITLE
AttributeError: 'float' object has no attribute 'item'

### ISSUE THREAD

**Issue by pasquale90** [val-iisc/lsc-cnn#33]
Hello! I tried to train for epochs from 0 to 3 and after finishing epoch 0 a message appears to re-run the code. Re-running train by using the same command I get the entitled error.. The full message is the following:

`
>>Training0...
>>LR: 0.001000000000.
>>Classification Model
>>/home/user/miniconda3/envs/lsc/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
>>Traceback (most recent call last):
>> File "main.py", line 1108, in <module>
>>    train()
>>  File "main.py", line 1049, in train
>>    log_path=model_save_path)
>>  File "main.py", line 897, in train_networks
>>    losses, hist_boxes, hist_boxes_gt = train_funcs[0](Xs, Ys, hist_boxes, hist_boxes_gt, loss_weights, network)
>>  File "main.py", line 343, in train_function
>>    losses.append(loss_.item())
>>AttributeError: 'float' object has no attribute 'item' 
`

Any clues would be appreciated !

**Comment by pasquale90** [comment]
To answer to my question, in line 343 of main.py, replacing the : 
`losses.append(loss_.item())`
with 
`losses.append(loss_)`
seems to produce no error anymore.. 

I close this issue but feel free to re-open it in case that you think I am wrong..
