### ISSUE TITLE
Error : Can't read meta data call create_dataset_files

### ISSUE THREAD

**Issue by MounirB** [val-iisc/lsc-cnn#5]
Hello, after downloading the st_parta dataset and running the following command :
`python main.py --dataset="parta" --gpu=2 --start-epoch=13 --epochs=13 --threshold=0.21`

I get the following error : 

```
In data_reader.__init__: Can't read meta data in ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30; call create_dataset_files.
{'test': ['../dataset/ST_partA/test_data/images', '../dataset/ST_partA/test_data/ground_truth'], 'train': ['../dataset/ST_partA/train_data/images', '../dataset/ST_partA/train_data/ground_truth']} <data_reader.DataReader object at 0x7f237be32ba8>
CREATING DATASET...
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30 does not exists; but created.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test created.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/train created.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test_valid created.
Processing IMG_1.jpg ...
Traceback (most recent call last):
  File "main.py", line 1096, in <module>
    train()
  File "main.py", line 1017, in train
    test_batch_size=4)
  File "/media/mounir/a1340c42-9115-49f7-9b0b-61e804384f0e/PycharmProjectsHDD/LSC-CNN-Counting/lsc-cnn/data_reader.py", line 200, in create_dataset_files
    self._dump_all_test_images(set_name)
  File "/media/mounir/a1340c42-9115-49f7-9b0b-61e804384f0e/PycharmProjectsHDD/LSC-CNN-Counting/lsc-cnn/data_reader.py", line 826, in _dump_all_test_images
    data = self._read_image_and_gt_prediction(paths, file_name, kernel)
  File "/media/mounir/a1340c42-9115-49f7-9b0b-61e804384f0e/PycharmProjectsHDD/LSC-CNN-Counting/lsc-cnn/data_reader.py", line 789, in _read_image_and_gt_prediction
    'GT_' + tmp + '.mat'))
  File "/home/mounir/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/mounir/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable
```
Can you tell me what is the error due to ?

**Comment by pvskand** [comment]
I think it's due to mismatch of names of `ground-truth` folder of `ST_PartA`. Could you please change your `ground-truth` folder in `train` and `test` to `ground_truth` (replace hyphen by underscore). Let me know if this was the problem. I'll change the source code accordingly.

**Comment by MounirB** [comment]
Yes, that was the error, thank you :+1: 

I launched the command and I get sometimes the following errors for some images : 
`In data_reader.create_heatmap: Error in annotations; 1 point(s) skipped.`

What does it do when 1 point is skipped ?

**Comment by pvskand** [comment]
Great! 
The 1 point(s) skipped is because we are dumping the dataset in 1/2 the input image scale, so during down sampling, there would be some points that would merge.

**Comment by pvskand** [comment]
Great!
The 1 point(s) skipped is because of the error in dataset annotations (points outside the image, negative locations etc.)
